Refactor/best practice2(image component)
NerdNextDoor-Technologies/PixelPerfect pull request #40
Opened 2024-07-15 09:52 UTC by Ribhav-Jain22

# Pull Request Template

## Description

refactored imageHelper.ts and imageModel.js for better reusability.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (non-breaking change which improves code readability and/or UI Improvement)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Yes
- [ ] No

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have fixed SonarCloud errors
- [ ] I have checked my code and corrected any misspellings

2024-07-15 16:03 UTC, ad-mittal commented on vue-project/src/helpers/ImageHelper.ts
> +export function resizedImageByFileSize(imageElement: HTMLImageElement, targetSizeInBytes: number): string {
resizeImageByFileSize
not 
resize**d**ImageByFileSize

2024-07-15 16:03 UTC, happypotter1993 commented on vue-project/src/helpers/ImageHelper.ts
> +export function resizedImageByFileSize(imageElement: HTMLImageElement, targetSizeInBytes: number): string {
Why does it return a string here?

2024-07-15 16:03 UTC, happypotter1993 commented on vue-project/src/helpers/ImageHelper.ts
> +export function resizeImageByResolution(imageElement: HTMLImageElement, targetImageResolution: { width: number; height: number }, qualityFactor: number = 1.0): string {
why does this function return a string?

2024-07-15 16:03 UTC, happypotter1993 commented on vue-project/src/helpers/ImageHelper.ts
> +    //2300x3400
remove this comment

2024-07-15 16:05 UTC, happypotter1993 commented on vue-project/src/models/image/ImageModel.ts
> +    this.currentResolution = new ImageResolution(1, 1);
This is wrong.
why are you setting defaults at all?
You can set all of these when the image is loaded

2024-07-15 16:07 UTC, happypotter1993 requested changes

2024-07-15 16:07 UTC, happypotter1993 commented on vue-project/src/models/image/ImageModel.ts
> +    this.currentResolution = new ImageResolution(1, 1);
This is wrong.
why are you setting defaults at all?
You can set all of these when the image is loaded

2024-07-15 16:15 UTC, Ribhav-Jain22 commented
I am working on it currently. Was fixing the ui issue.

On Mon, 15 Jul 2024, 9:37 pm Aditya Mittal, ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In vue-project/src/models/image/ImageModel.ts
> <https://github.com/NerdNextDoor-Technologies/PixelPerfect/pull/40#discussion_r1678076232>
> :
>
> > @@ -0,0 +1,52 @@
> +// models/image/ImageModel.js
> +import { LogError } from '@/helpers/LogHelper/LogError';
> +import { ImageResolution } from './ImageResolution';
> +export class ImageData {
> +
> +  targetWidth: number
> +  targetHeight: number
> +  currentImageSrc: string;
> +  currentFileSize: number;
> +  currentFileName: string;
> +  currentResolution: ImageResolution;
> +
> +  constructor(file) {
> +
> +    this.currentResolution = new ImageResolution(1, 1);
>
> This is wrong.
> why are you setting defaults at all?
> You can set all of these when the image is loaded
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/NerdNextDoor-Technologies/PixelPerfect/pull/40#pullrequestreview-2178135270>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BFBW2F6P5MXFP6EMVCRKBSLZMPXUVAVCNFSM6AAAAABK4GMHJ6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCNZYGEZTKMRXGA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>

2024-07-18 11:51 UTC, happypotter1993 approved these changes

2024-07-18 11:51 UTC, merged